theme: jekyll-theme-hacker
title: root💀the.opemi.aa-sec:~#
description: On a mission to save planet earth! Hack. Eat. Sleep. Repeat.
show_downloads: false
show_repo: false

gems:
- jekyll-sitemap

whitelist:
- jekyll-sitemap
